# Generated by Django 3.2 on 2023-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='address',
        ),
        migrations.AddField(
            model_name='box',
            name='load_address',
            field=models.CharField(max_length=200, null=True, verbose_name='도로명주소'),
        ),
        migrations.AddField(
            model_name='box',
            name='lot_address',
            field=models.CharField(max_length=200, null=True, verbose_name='지번주소'),
        ),
        migrations.AlterField(
            model_name='box',
            name='type',
            field=models.CharField(choices=[('C', '의류수거함'), ('B', '건전지수거함'), ('F', '형광등수거함')], max_length=50, verbose_name='수거함타입'),
        ),
    ]
