# Generated by Django 3.2 on 2023-05-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20230529_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='x',
            field=models.FloatField(default=0, verbose_name='X 좌표'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='y',
            field=models.FloatField(default=0, verbose_name='Y 좌표'),
            preserve_default=False,
        ),
    ]
